package com.josiprezic.projecteuler;

/*Problem 2
*Even Fibonacci numbers
*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
* */

public class Task2 {

    static void run() {

        long firstNumber = 1;
        long secondNumber = 2;
        long sum = 2;
        long temp;

        while(firstNumber < 4000000 && secondNumber < 4000000) {
            temp = firstNumber + secondNumber;
            firstNumber = secondNumber;
            secondNumber = temp;
            sum += (temp % 2 == 0) ? temp : 0;
        }

        System.out.println("TASK 2: " + sum);
    }
}
